import React, {useState, useEffect} from 'react'
import { Card, Loader, FormField } from '../components/ComponentExport'

const Home = () => {
  const [loading, setloading] = useState(false)
  
  const [allPosts, setAllPosts] = useState(null)

  return (
    
    <section className="max-w-7xl mx-auto">
      <h1 className="text-2xl font-bold text-[#222328]">The community showcase</h1>
      <p className='mt-2 text-[#666e67] text-[16px] xam-w-[500px]'>Browse through a collection of stunnishing and imaginative images generated by DALL-E AI</p>

      <div>
        
      </div>

    </section>
  )
}

export default Home